name: 'Uninstall homebrew'
description: 'Run the official homebrew uninstall script'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        brew install --cask xquartz 2>&1 | sed 's/^Warning/Note/'
    - shell: bash
      run: |
        curl -fsSOL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
        sudo bash uninstall.sh --force --quiet 2>&1 | sed 's/Warning/Note/g'
        hash -r && rm uninstall.sh
    - shell: bash
      run: |
        curl -sSL http://dl.bintray.com/autobrew/high_sierra/gdal-3.2.0-high_sierra.tar.xz -o libs.tar.xz
        sudo tar -xf libs.tar.xz --strip 1 -C /usr/local/
        rm -f libs.tar.xz
        echo "PROJ_LIB=/usr/local/share/proj" >> $GITHUB_ENV
