name: 'Uninstall homebrew'
description: 'Run the homebrew uninstall script'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "Removing Homebrew..."
        cp $(which gtar) $(which zstd) .
        curl -fsSOL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
        sudo bash uninstall.sh --force --quiet 2>&1 | sed 's/Warning/Note/g'
        cp -f gtar zstd /usr/local/bin/
        hash -r && rm uninstall.sh
        echo "Done removing homebrew!"
    - shell: bash
      run: |
        echo "Installing GDAL bundle..."
        curl -sSL http://dl.bintray.com/autobrew/high_sierra/gdal-3.2.0-high_sierra.tar.xz -o libs.tar.xz
        sudo tar -xf libs.tar.xz --strip 1 -C /usr/local/
        rm -f libs.tar.xz
        echo "Done installing GDAL!"
    - shell: bash
      run:
        echo "Setting path to proj and fortran"
        echo "PROJ_LIB=/usr/local/share/proj" >> $GITHUB_ENV
        echo "/usr/local/gfortran/bin" >> $GITHUB_PATH
