name: 'Uninstall homebrew'
description: 'Run the homebrew uninstall script'
runs:
  using: "composite"
  steps:
    - shell: bash
      name: Run homebrew uninstall script
      run: |
        echo "Removing Homebrew..."
        brew install gnu-tar zstd checkbashisms || true
        cp $(which gtar) $(which zstd) $(which checkbashisms) .
        curl -fsSOL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
        sudo bash uninstall.sh --force --quiet 2>&1 | sed 's/Warning/Note/g'
        mv -f gtar zstd checkbashisms /usr/local/bin/
        hash -r && rm uninstall.sh
        echo "Done removing homebrew!"

    - shell: bash
      name: Install xQuartz if needed
      run: |
        if [ -d "/opt/X11/lib" ]; then
          echo "/opt/X11/lib exists. Skipping xQuartz installation"
        else
          echo "Downloading XQuartz..."
          curl -fLo XQuartz-2.7.11.dmg https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
          sudo hdiutil attach XQuartz-2.7.11.dmg -mountpoint /Volumes/xquartz
          sudo installer -pkg "/Volumes/xquartz/XQuartz.pkg" -target /
          sudo hdiutil detach /Volumes/xquartz
          rm -f XQuartz-2.7.11.dmg
          echo "Done installing XQuartz!"
        fi

    - shell: bash
      name: Install pandoc if needed
      run: |
        if pandoc --version; then
          echo "Skipping pandoc installation"
        else
          curl -fOL https://github.com/jgm/pandoc/releases/download/2.11.4/pandoc-2.11.4-macOS.pkg
          sudo installer -pkg pandoc-2.11.4-macOS.pkg -target /
          rm -f pandoc-2.11.4-macOS.pkg
        fi
